version: 2

jobs:

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run: npm test

  release:
    docker:
      - image: circleci/node:latest
    steps:
      - run: npx semantic-release

  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - test
      - release:
          requires:
            - test